/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as MandateRouteImport } from './routes/mandate'
import { Route as PreSellRouteImport } from './routes/presell'
import { Route as PropertyManagementRouteImport } from './routes/property-management'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const MandateRoute = MandateRouteImport.update({
  id: '/mandate',
  path: '/mandate',
  getParentRoute: () => rootRouteImport,
} as any)
const PreSellRoute = PreSellRouteImport.update({
  id: '/presell',
  path: '/presell',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyManagementRoute = PropertyManagementRouteImport.update({
  id: '/property-management',
  path: '/property-management',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/about': typeof AboutRoute
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/mandate': typeof MandateRoute
  '/presell': typeof PreSellRoute
  '/property-management': typeof PropertyManagementRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/mandate': typeof MandateRoute
  '/presell': typeof PreSellRoute
  '/property-management': typeof PropertyManagementRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/about': typeof AboutRoute
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/mandate': typeof MandateRoute
  '/presell': typeof PreSellRoute
  '/property-management': typeof PropertyManagementRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/about' | '/' | '/faq' | '/mandate' | '/presell' | '/property-management'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/' | '/faq' | '/mandate' | '/presell' | '/property-management'
  id: '__root__' | '/about' | '/' | '/faq' | '/mandate' | '/presell' | '/property-management'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AboutRoute: typeof AboutRoute
  IndexRoute: typeof IndexRoute
  FaqRoute: typeof FaqRoute
  MandateRoute: typeof MandateRoute
  PreSellRoute: typeof PreSellRoute
  PropertyManagementRoute: typeof PropertyManagementRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mandate': {
      id: '/mandate'
      path: '/mandate'
      fullPath: '/mandate'
      preLoaderRoute: typeof MandateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presell': {
      id: '/presell'
      path: '/presell'
      fullPath: '/presell'
      preLoaderRoute: typeof PreSellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property-management': {
      id: '/property-management'
      path: '/property-management'
      fullPath: '/property-management'
      preLoaderRoute: typeof PropertyManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AboutRoute: AboutRoute,
  IndexRoute: IndexRoute,
  FaqRoute: FaqRoute,
  MandateRoute: MandateRoute,
  PreSellRoute: PreSellRoute,
  PropertyManagementRoute: PropertyManagementRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
